import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

const html = readFileSync('index.html', 'utf8');
const css = readFileSync('styles.css', 'utf8');
const js = readFileSync('app.js', 'utf8');
const scheduleHtml = readFileSync('schedule.html', 'utf8');
const scheduleCss = readFileSync('schedule.css', 'utf8');
const scheduleJs = readFileSync('schedule.js', 'utf8');
const entryHtml = readFileSync('entry-service.html', 'utf8');
const entryCss = readFileSync('entry-service.css', 'utf8');
const entryJs = readFileSync('entry-service.js', 'utf8');
const profileHtml = readFileSync('profile.html', 'utf8');
const profileCss = readFileSync('profile.css', 'utf8');
const profileJs = readFileSync('profile.js', 'utf8');
const boardHtml = readFileSync('page-board.html', 'utf8');
const boardCss = readFileSync('page-board.css', 'utf8');
const boardJs = readFileSync('page-board.js', 'utf8');

assert.match(html, /viewport-fit=cover/);
assert.doesNotMatch(html, /user-scalable=no|maximum-scale=1/);
assert.doesNotMatch(html, /class="status-bar"|9:41/);
assert.match(html, /<main class="app-shell" data-ui-ready="true">/);
assert.match(html, /<dialog[^>]+id="action-dialog"/);
assert.match(css, /^@import "\.\/design-system\/tokens\/design-tokens\.css";/);
assert.match(css, /100dvh/);
assert.match(css, /env\(safe-area-inset-top/);
assert.match(css, /env\(safe-area-inset-bottom/);
assert.match(css, /prefers-reduced-motion/);
assert.doesNotMatch(css, /outline:\s*none/);
assert.doesNotMatch(css, /url\([^)]*codex-clipboard/);
assert.doesNotMatch(js, /innerHTML|insertAdjacentHTML|eval\(/);

assert.match(scheduleHtml, /viewport-fit=cover/);
assert.doesNotMatch(scheduleHtml, /user-scalable=no|maximum-scale=1/);
assert.doesNotMatch(scheduleHtml, /class="status-bar"|9:41/);
assert.match(scheduleHtml, /data-ui-ready="false"/);
assert.match(scheduleHtml, /aria-current="page"/);
assert.match(scheduleHtml, /role="tablist"/);
assert.match(scheduleCss, /^@import "\.\/design-system\/tokens\/design-tokens\.css";/);
assert.match(scheduleCss, /100dvh/);
assert.match(scheduleCss, /env\(safe-area-inset-top/);
assert.match(scheduleCss, /env\(safe-area-inset-bottom/);
assert.match(scheduleCss, /prefers-reduced-motion/);
assert.doesNotMatch(scheduleCss, /outline:\s*none/);
assert.doesNotMatch(scheduleCss, /url\([^)]*codex-clipboard/);
assert.doesNotMatch(scheduleJs, /innerHTML|insertAdjacentHTML|eval\(/);

assert.match(entryHtml, /viewport-fit=cover/);
assert.doesNotMatch(entryHtml, /user-scalable=no|maximum-scale=1/);
assert.doesNotMatch(entryHtml, /class="status-bar"|>9:41</);
assert.match(entryHtml, /<main class="entry-shell" data-ui-ready="true">/);
assert.match(entryHtml, /<dialog[^>]+id="entry-dialog"/);
assert.match(entryCss, /^@import "\.\/design-system\/tokens\/design-tokens\.css";/);
assert.match(entryCss, /100dvh/);
assert.match(entryCss, /env\(safe-area-inset-top/);
assert.match(entryCss, /env\(safe-area-inset-bottom/);
assert.match(entryCss, /prefers-reduced-motion/);
assert.doesNotMatch(entryCss, /outline:\s*none/);
assert.doesNotMatch(entryCss, /url\([^)]*codex-clipboard/);
assert.doesNotMatch(entryJs, /innerHTML|insertAdjacentHTML|eval\(/);

assert.match(profileHtml, /viewport-fit=cover/);
assert.doesNotMatch(profileHtml, /user-scalable=no|maximum-scale=1/);
assert.doesNotMatch(profileHtml, /class="status-bar"|>9:41</);
assert.match(profileHtml, /<main class="profile-shell" data-ui-ready="true">/);
assert.match(profileHtml, /<dialog[^>]+id="profile-dialog"/);
assert.match(profileCss, /^@import "\.\/design-system\/tokens\/design-tokens\.css";/);
assert.match(profileCss, /max-width:375px/);
assert.match(profileCss, /\.profile-shell,\.profile-tabbar\{max-width:var\(--layout-wide-canvas\)/);
assert.match(profileCss, /100dvh/);
assert.match(profileCss, /env\(safe-area-inset-top/);
assert.match(profileCss, /env\(safe-area-inset-bottom/);
assert.match(profileCss, /prefers-reduced-motion/);
assert.doesNotMatch(profileCss, /outline:\s*none/);
assert.doesNotMatch(profileCss, /url\([^)]*codex-clipboard/);
assert.doesNotMatch(profileJs, /innerHTML|insertAdjacentHTML|eval\(/);

assert.match(boardHtml, /viewport-fit=cover/);
assert.doesNotMatch(boardHtml, /user-scalable=no|maximum-scale=1/);
assert.match(boardHtml, /<main class="page-board" data-ui-ready="false">/);
assert.match(boardHtml, /<iframe[^>]+id="page-preview"/);
assert.match(boardCss, /^@import "\.\/design-system\/tokens\/design-tokens\.css";/);
assert.match(boardCss, /--board-preview-width:750px/);
assert.match(boardCss, /@media \(max-width:900px\)/);
assert.match(boardCss, /prefers-reduced-motion/);
assert.doesNotMatch(boardCss, /outline:\s*none/);
assert.doesNotMatch(boardCss, /url\([^)]*codex-clipboard/);
assert.match(boardJs, /const pages = Object\.freeze/);
assert.doesNotMatch(boardJs, /innerHTML|insertAdjacentHTML|eval\(/);

console.log('Static production checks passed.');
